package com._Blog.app.like.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

import com._Blog.app.user.entity.User;
import com._Blog.app.post.entity.Post;

// Maps this class to the "likes" table in the database
@Entity
@Table(name = "likes")
public class Like {

    // Primary key — auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Many likes can belong to one post
    // post_id is the foreign key column in the likes table
    @ManyToOne
    @JoinColumn(name = "post_id", nullable = false)
    private Post post;

    // Many likes can be given by one user
    // user_id is the foreign key column in the likes table
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // Set automatically when the like is first created
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    public Like() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Post getPost() {
        return post;
    }

    public void setPost(Post post) {
        this.post = post;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
