package com._Blog.app.subscription.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

import com._Blog.app.user.entity.User;

// Maps this class to the "subscriptions" table in the database
// A subscription means one user follows another user
@Entity
@Table(name = "subscriptions")
public class Subscription {

    // Primary key — auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The user who is doing the following (the follower)
    // subscriber_id is the foreign key column in the subscriptions table
    @ManyToOne
    @JoinColumn(name = "subscriber_id", nullable = false)
    private User subscriber;

    // The user being followed (the target of the subscription)
    // target_id is the foreign key column in the subscriptions table
    @ManyToOne
    @JoinColumn(name = "target_id", nullable = false)
    private User target;

    // Set automatically when the subscription is first created
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    public Subscription() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User getSubscriber() {
        return subscriber;
    }

    public void setSubscriber(User subscriber) {
        this.subscriber = subscriber;
    }

    public User getTarget() {
        return target;
    }

    public void setTarget(User target) {
        this.target = target;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
