package com._Blog.app.comment.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

import com._Blog.app.user.entity.User;
import com._Blog.app.post.entity.Post;

// Maps this class to the "comments" table in the database
@Entity
@Table(name = "comments")
public class Comment {

    // Primary key — auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Many comments can belong to one post
    // post_id is the foreign key column in the comments table
    @ManyToOne
    @JoinColumn(name = "post_id", nullable = false)
    private Post post;

    // Many comments can be written by one user (author)
    // user_id is the foreign key column in the comments table
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User author;

    // The text body of the comment
    @Column(nullable = false, columnDefinition = "TEXT")
    private String content;

    // Set automatically when the comment is first created
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    public Comment() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Post getPost() {
        return post;
    }

    public void setPost(Post post) {
        this.post = post;
    }

    public User getAuthor() {
        return author;
    }

    public void setAuthor(User author) {
        this.author = author;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
