package com._Blog.app.report.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

import com._Blog.app.user.entity.User;
import com._Blog.app.post.entity.Post;

// Maps this class to the "reports" table in the database
// A report is filed by one user against another user or a post
@Entity
@Table(name = "reports")
public class Report {

    // Primary key — auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The user who submitted the report
    // reporter_id is the foreign key column in the reports table
    @ManyToOne
    @JoinColumn(name = "reporter_id", nullable = false)
    private User reporter;

    // The user being reported (optional — can report a post without a specific
    // user)
    // reported_user_id is the foreign key column in the reports table
    @ManyToOne
    @JoinColumn(name = "reported_user_id")
    private User reportedUser;

    // The post being reported (optional — can report a user without a specific
    // post)
    // reported_post_id is the foreign key column in the reports table
    @ManyToOne
    @JoinColumn(name = "reported_post_id")
    private Post reportedPost;

    // The explanation provided by the reporter
    @Column(nullable = false, columnDefinition = "TEXT")
    private String reason;

    // Current state of the report (e.g. "pending", "resolved", "dismissed")
    @Column
    private String status;

    // Set automatically when the report is first created
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    public Report() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User getReporter() {
        return reporter;
    }

    public void setReporter(User reporter) {
        this.reporter = reporter;
    }

    public User getReportedUser() {
        return reportedUser;
    }

    public void setReportedUser(User reportedUser) {
        this.reportedUser = reportedUser;
    }

    public Post getReportedPost() {
        return reportedPost;
    }

    public void setReportedPost(Post reportedPost) {
        this.reportedPost = reportedPost;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
