package com._Blog.app.notification.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

import com._Blog.app.user.entity.User;
import com._Blog.app.post.entity.Post;

// Maps this class to the "notifications" table in the database
@Entity
@Table(name = "notifications")
public class Notification {

    // Primary key — auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The user who receives this notification
    // recipient_id is the foreign key column in the notifications table
    @ManyToOne
    @JoinColumn(name = "recipient_id", nullable = false)
    private User recipient;

    // The post this notification is linked to (optional)
    // related_post_id is the foreign key column in the notifications table
    @ManyToOne
    @JoinColumn(name = "related_post_id")
    private Post relatedPost;

    // The kind of notification (e.g. "like", "comment", "follow")
    @Column(nullable = false)
    private String type;

    // A human-readable description of what happened
    @Column
    private String message;

    // false by default — becomes true once the user reads the notification
    @Column(name = "is_read", nullable = false)
    private Boolean isRead = false;

    // Set automatically when the notification is first created
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    public Notification() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User getRecipient() {
        return recipient;
    }

    public void setRecipient(User recipient) {
        this.recipient = recipient;
    }

    public Post getRelatedPost() {
        return relatedPost;
    }

    public void setRelatedPost(Post relatedPost) {
        this.relatedPost = relatedPost;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
