package com._Blog.app.user.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

// Maps this class to the "users" table in the database
@Entity
@Table(name = "users")
public class User {

    // Primary key — auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // unique = true → no two users can share the same username
    @Column(nullable = false, unique = true)
    private String username;

    // unique = true → no two users can share the same email
    @Column(nullable = false, unique = true)
    private String email;

    // Stores the BCrypt hash of the password, never the plain text
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    // Role of the user : USER or ADMIN
    @Column
    private String role;

    // Short description the user writes about themselves
    @Column(columnDefinition = "TEXT")
    private String bio;

    // URL pointing to the user's profile picture
    @Column(name = "avatar_url")
    private String avatarUrl;

    // Set automatically when the user is first created
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    public User() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getBio() {
        return bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
