package com._Blog.app.user.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import com._Blog.app.comment.entity.Comment;
import com._Blog.app.like.entity.Like;
import com._Blog.app.notification.entity.Notification;
import com._Blog.app.post.entity.Post;
import com._Blog.app.report.entity.Report;
import com._Blog.app.subscription.entity.Subscription;

// Maps this class to the "users" table in the database
@Entity
@Table(name = "users")
public class User {

    // Primary key — auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // unique = true → no two users can share the same username
    @Column(nullable = false, unique = true)
    private String username;

    // unique = true → no two users can share the same email
    @Column(nullable = false, unique = true)
    private String email;

    // Stores the BCrypt hash of the password, never the plain text
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    // Role of the user : USER or ADMIN
    @Column
    private String role;

    // Short description the user writes about themselves
    @Column(columnDefinition = "TEXT")
    private String bio;

    // URL pointing to the user's profile picture
    @Column(name = "avatar_url")
    private String avatarUrl;

    // Set automatically when the user is first created
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    // Everything below points at an existing @ManyToOne field on the child entity, so it
    // is the inverse side of the relationship and creates no database column. The two
    // Subscription and two Report mappings are both needed: a user sits on both sides of
    // those tables, and leaving either one out keeps rows that block the user delete.

    @JsonIgnore
    @OneToMany(mappedBy = "author", cascade = CascadeType.REMOVE)
    private List<Post> posts = new ArrayList<>();

    @JsonIgnore
    @OneToMany(mappedBy = "author", cascade = CascadeType.REMOVE)
    private List<Comment> comments = new ArrayList<>();

    @JsonIgnore
    @OneToMany(mappedBy = "user", cascade = CascadeType.REMOVE)
    private List<Like> likes = new ArrayList<>();

    @JsonIgnore
    @OneToMany(mappedBy = "subscriber", cascade = CascadeType.REMOVE)
    private List<Subscription> subscriptions = new ArrayList<>();

    @JsonIgnore
    @OneToMany(mappedBy = "target", cascade = CascadeType.REMOVE)
    private List<Subscription> followers = new ArrayList<>();

    @JsonIgnore
    @OneToMany(mappedBy = "recipient", cascade = CascadeType.REMOVE)
    private List<Notification> notifications = new ArrayList<>();

    @JsonIgnore
    @OneToMany(mappedBy = "reporter", cascade = CascadeType.REMOVE)
    private List<Report> reportsFiled = new ArrayList<>();

    @JsonIgnore
    @OneToMany(mappedBy = "reportedUser", cascade = CascadeType.REMOVE)
    private List<Report> reportsAgainst = new ArrayList<>();

    public User() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getBio() {
        return bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public List<Post> getPosts() {
        return posts;
    }

    public List<Comment> getComments() {
        return comments;
    }

    public List<Like> getLikes() {
        return likes;
    }

    public List<Subscription> getSubscriptions() {
        return subscriptions;
    }

    public List<Subscription> getFollowers() {
        return followers;
    }

    public List<Notification> getNotifications() {
        return notifications;
    }

    public List<Report> getReportsFiled() {
        return reportsFiled;
    }

    public List<Report> getReportsAgainst() {
        return reportsAgainst;
    }
}

/*  

┌─────────────────────────────────────────────────────────┐
│ users                                                   │
├──────────────┬──────────────┬───────────────────────────┤
│ Column       │ Java type    │ Description               │
├──────────────┼──────────────┼───────────────────────────┤
│ id           │ Long         │ Primary key               │
│ username     │ String       │ Unique username           │
│ email        │ String       │ Unique email              │
│ password_hash│ String       │ BCrypt password hash      │
│ role         │ String       │ USER or ADMIN             │
│ bio          │ String       │ User description          │
│ avatar_url   │ String       │ Profile image URL         │
│ created_at   │ LocalDateTime│ Account creation date     │
└──────────────┴──────────────┴───────────────────────────┘

*/