package com._Blog.app.post.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

import com._Blog.app.user.entity.User;

// Maps this class to the "posts" table in the database
@Entity
@Table(name = "posts")
public class Post {

    // Primary key — auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Many posts can belong to one user (author)
    // user_id is the foreign key column in the posts table
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User author;

    // The main body of the post
    @Column(nullable = false, columnDefinition = "TEXT")
    private String content;

    // Optional: URL of an image or video attached to the post
    @Column(name = "media_url")
    private String mediaUrl;

    // Optional: type of the media (e.g. "image", "video")
    @Column(name = "media_type")
    private String mediaType;

    // If true, the post is hidden from public feed (soft delete / moderation)
    @Column(nullable = false)
    private Boolean hidden = false;

    // Set automatically when the post is first created
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    // Updated every time the post content is edited
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    public Post() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User getAuthor() {
        return author;
    }

    public void setAuthor(User author) {
        this.author = author;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getMediaUrl() {
        return mediaUrl;
    }

    public void setMediaUrl(String mediaUrl) {
        this.mediaUrl = mediaUrl;
    }

    public String getMediaType() {
        return mediaType;
    }

    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }

    public Boolean getHidden() {
        return hidden;
    }

    public void setHidden(Boolean hidden) {
        this.hidden = hidden;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
